### ISSUE TITLE
update to 2.0 miss some files

### ISSUE THREAD

**Issue by maxalone** [Luidog/node-red-contrib-filemaker#19]
in windows environment after update to 2.0 in node-red palette there are notifications that some files under \systemprofile\.node-red\node_modules\node-red-contrib-filemaker\src\client\ does not exist like \databases.html  \productInfo.html \duplicate.html \layouts.html \layout.html \scripts.html

apparently everything seems to work

**Comment by Luidog** [comment]
@maxalone The 2.0.1 release should resolve the missing files. Please reopen this issue if not.

 https://github.com/Luidog/node-red-contrib-filemaker/releases/tag/2.0.1
