### ISSUE TITLE
Add "node-red" keyword for listing in flows.nodered.org library

### ISSUE THREAD

**Issue by echoix** [Luidog/node-red-contrib-filemaker#38]
The package.json and thus the npm page uses the "Node-RED" keyword. For the package to be found in the flow library at https://flows.nodered.org/, it must have the "node-red" keyword. 

Also, since April 2020, after pushing to npm, you need to login the flows.nodered.org and press "Request refresh" for the package to appear as updatable in the interface. https://discourse.nodered.org/t/how-to-add-update-nodes-to-the-flow-library/25294

This package seems well documented and it would be great for it to be findable in the library!

**Comment by dani-phillips** [comment]
Please do this. I'm having trouble installing via npm with node-red and really need this.

**Comment by Luidog** [comment]
The project should be available [here](https://flows.nodered.org/node/node-red-contrib-filemaker#). Let me know if you folks have any issues finding it.

**Comment by echoix** [comment]
Perfect!
