### ISSUE TITLE
httpstat.us down, causing tests to fail

### ISSUE THREAD

**Issue by belac9615** [Luidog/node-red-contrib-filemaker#43]
The https://httpstat.us/ website is down causing tests to fail. We need to mock API responses to prevent this in the future and allow offline testing. I'll take a stab at it.

**Comment by belac9615** [comment]
This came up in a previous PR https://github.com/Luidog/node-red-contrib-filemaker/pull/41#issuecomment-704979456

**Comment by belac9615** [comment]
@Luidog I was not able to make any progress on this. I had trouble setting up a dev environment that would run the existing tests successfully. Snyk throws this error:

> `snyk` requires an authenticated account. Please run `snyk auth` and try again.

Is there a way to share snyk authentication? Do I just make my own account?

**Comment by Luidog** [comment]
Thanks for taking a pass at it @belac9615. When I integrated snyk into this project it did not require an account. I am going to adjust the project to only require a snyk account for tests on master. You can run the tests using:

`nyc _mocha --recursive \"test/**/*_spec.js\" --timeout=30000 --exit`

**Comment by Luidog** [comment]
The https://httpstat.us/ website is back up. I am closing this issue. I would still accept a pull request mocking the requests for test which require an error response.
