### ISSUE TITLE
Error on Install - node-red-contrib-filemaker 2.3.1

### ISSUE THREAD

**Issue by bduck** [Luidog/node-red-contrib-filemaker#44]
Thanks for your efforts, 

I just viewed "FileMaker of Things: APIs and IoT Using Node Red [INT08]." Awesome demo!

I'm installing on a fresh build of R-PI Debian, Node-RED, then node-red-contrib-filemaker 2.3.1

Error generated is:
2020-10-12T00:08:45.914Z [err]  ERR! Unexpected end of JSON input while parsing near '...OENx1CUxjIXup/yMbwfMF'

I'm unsure if I need to install dependencies prior to node-red-contrib-filemaker 2.3.1, please advise if ID10T is at fault.

Bduck at Mac com

**Comment by Luidog** [comment]
Sorry @bduck, I don't think this is an issue with the module itself. I would recommend clearing npm's cache.
